export default {
    'APP_START': 'APP_START',
    'APP_STOP': 'APP_STOP',
    'APP_UPDATE_FILTER': 'APP_UPDATE_FILTER',
    'VIDEO_LIST_UPDATE': 'VIDEO_LIST_UPDATE',
    'VIDEO_LIST_LOADING': 'VIDEO_LIST_LOADING',
    'VIDEO_DETAIL_UPDATE': 'VIDEO_DETAIL_UPDATE',
    'VIDEO_UPDATE': 'VIDEO_UPDATE',
}
